version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-qa
    ports:
      - "${PORT:-9000}:${PORT:-9000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-9000}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
    command: node ./app.js
    restart: unless-stopped
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge
