version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: resume-qa
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    command: node app.js
    restart: unless-stopped
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge 